services:
    goaccess:
        build:
            context: .
        container_name: goaccess
        ports:
            - '8080:8080'
        volumes:
            - ./haproxy_logs:/logs:ro
        command: ['/bin/bash', '/run.sh']
